### ISSUE TITLE
force_restart_queue and queue_empty command not working

### ISSUE THREAD

**Issue by thewickerman22** [yannickgloster/discord-10man#89]
**Describe the bug**
when doing a pug once players have joined the vc and team selection has begun this command shud restart the queuing or the empty command shud disconnect all the players from the queue lobby. but when force_restart_queue command is given it throws an error no queue running.

**To Reproduce**
join a vc start a pug with captains. during player selection run this command. force_restart_queue will throw an error no queue running and empty queue command does nothin.

**Expected behavior**
on empty queue command it should cancel the team selection process and transfer the players to another vc like pre-lobby basically empty the queue channel.
on force restart queue restart the team selection process

**Comment by yannickgloster** [comment]
@thewickerman22 
That is not what `empty queue` or `force_restart_queue` is for.
Once a pug starts and the veto starts, there isn't a good way to end it with the way the current. All that empty queue does is kick everyone out of the voice channel for a queue, if a veto is in progress, you're going to probably break everything.
Force restart queue restarts the processes that checks if the queue is full.
Again you can't stop a veto while it's happening.
If you want to be able to do that, please open a feature request because that will take a lot of restructuring.
